"use client";
import React, { useState } from "react";
import {
  Typography,
  Card,
  Form,
  Button,
  message,
  Steps,
  Input,
  Result,
  Layout,
  Row,
  Col,
  Badge,
  Avatar,
  Space,
} from "antd";
import { useUserState } from "@/providers/user-provider";
import { useFitnessPathActions } from "@/providers/fitnesspath/fitness-provider";
import ActivityTypes from "../../components/path-sign-up/fitness/activity-ai";
import ExercisePlanBuilder from "../../components/path-sign-up/fitness/exercise-plan";
import { useRouter } from "next/navigation";
import {
  RocketOutlined,
  CheckCircleOutlined,
  TrophyOutlined,
  FireOutlined,
  ArrowLeftOutlined,
  ArrowRightOutlined,
  UserOutlined,
} from "@ant-design/icons";

const { Title, Paragraph, Text } = Typography;
const { Content } = Layout;

// Custom styling for the theme
const theme = {
  colors: {
    primary: "#F23D5E",
    secondary: "#D9328E",
    tertiary: "#BF3FB7",
    accent1: "#F24141",
    accent2: "#FB765C",
    lightGray: "#f7f7f7",
    darkGray: "#333333",
    white: "#FFFFFF",
  },
  gradients: {
    main: "linear-gradient(90deg, #F23D5E 0%, #D9328E 50%, #BF3FB7 100%)",
    secondary: "linear-gradient(90deg, #F24141 0%, #FB765C 100%)",
  },
};

// Custom styles for components
const styles = {
  welcomeCard: {
    backgroundImage: theme.gradients.main,
    borderRadius: "12px",
    boxShadow: "0 8px 16px rgba(242, 61, 94, 0.15)",
    color: theme.colors.white,
    padding: "24px",
    marginBottom: "32px",
    border: "none",
  },
  welcomeTitle: {
    color: theme.colors.white,
    fontSize: "32px",
    fontWeight: "bold",
    marginBottom: "12px",
  },
  welcomeText: {
    color: theme.colors.white,
    fontSize: "16px",
    opacity: "0.9",
  },
  container: {
    maxWidth: "1200px",
    margin: "0 auto",
    padding: "32px 24px",
  },
  stepCard: {
    borderRadius: "12px",
    boxShadow: "0 4px 12px rgba(0, 0, 0, 0.08)",
    marginTop: "32px",
    background: theme.colors.white,
  },
  button: {
    background: theme.colors.primary,
    borderColor: theme.colors.primary,
    borderRadius: "6px",
    height: "40px",
    fontWeight: "500",
  },
  secondaryButton: {
    borderColor: theme.colors.darkGray,
    borderRadius: "6px",
    height: "40px",
    fontWeight: "500",
  },
  statsCard: {
    background: theme.colors.lightGray,
    borderRadius: "8px",
    padding: "16px",
    height: "100%",
    TextAlign: "center",
  },
  badge: {
    backgroundColor: theme.colors.secondary,
    color: theme.colors.white,
    fontSize: "14px",
    padding: "4px 12px",
    borderRadius: "16px",
  },
  steps: {
    colorPrimary: theme.colors.primary,
  },
};

interface FitnessPathFormValues {
  name: string;
  description: string;
  fitnessGoal: string;
}

// Stats component to display on welcome page
const FitnessStats = () => (
  <Row gutter={[16, 16]} style={{ marginTop: "32px" }}>
    <Col xs={24} sm={8}>
      <Card style={styles.statsCard}>
        <FireOutlined
          style={{
            fontSize: "28px",
            color: theme.colors.accent1,
            marginBottom: "8px",
          }}
        />
        <Title level={4}>85%</Title>
        <Text type="secondary">Success Rate</Text>
      </Card>
    </Col>
    <Col xs={24} sm={8}>
      <Card style={styles.statsCard}>
        <TrophyOutlined
          style={{
            fontSize: "28px",
            color: theme.colors.secondary,
            marginBottom: "8px",
          }}
        />
        <Title level={4}>10+</Title>
        <Text type="secondary">Active Users</Text>
      </Card>
    </Col>
    <Col xs={24} sm={8}>
      <Card style={styles.statsCard}>
        <CheckCircleOutlined
          style={{
            fontSize: "28px",
            color: theme.colors.tertiary,
            marginBottom: "8px",
          }}
        />
        <Title level={4}>3+</Title>
        <Text type="secondary">Exercise Types</Text>
      </Card>
    </Col>
  </Row>
);

// Enhanced StepBasedFitnessPlanner component
const StepBasedFitnessPlanner: React.FC<{
  personId: string;
}> = ({ personId }) => {
  const { currentUser } = useUserState();
  const { createFitnessPath } = useFitnessPathActions();
  const [form] = Form.useForm<FitnessPathFormValues>();
  const [fitnessPathId, setFitnessPathId] = useState<string | null>(null);
  const router = useRouter();
  const [current, setCurrent] = useState(0);
  const [submitting, setSubmitting] = useState(false);
  const [activityTypes, setActivityTypes] = useState([]);

  // Handle activity types being generated by the ActivityTypes component
  const handleActivityTypesGenerated = (generatedActivityTypes) => {
    const formatted = generatedActivityTypes.map((activity) => ({
      id: activity.id,
      content: `${activity.category} (Intensity: ${activity.intensityLevel})`,
      category: activity.category,
      intensityLevel: activity.intensityLevel,
      description: activity.description,
    }));

    setActivityTypes(formatted);
  };

  const goDashboard = () => {
    router.push("/fitness-path");
  };

  // Handle basic info form submission
  const handleBasicInfoSubmit = async (values: FitnessPathFormValues) => {
    if (!personId) {
      message.error("Person ID is missing. Please log in again.");
      return;
    }

    setSubmitting(true);

    try {
      const fitnessPath = {
        title: values.name,
        description: values.description,
        fitnessGoal: values.fitnessGoal, // Added fitness goal field
        stepEntryIds: [],
        weightEntryIds: [],
        activityIds: [],
        personId: personId,
        exercisePlans: [],
      };

      // Await the result and store the ID
      const createdPath = await createFitnessPath(fitnessPath);

      setFitnessPathId(createdPath.id);

      message.success("Basic information saved!");
      setCurrent(1);
    } catch (error) {
      console.error("Error creating fitness path:", error);
      message.error("Failed to create fitness path.");
    } finally {
      setSubmitting(false);
    }
  };

  // Handle exercise plan submission
  const handleExercisePlanSubmit = () => {
    message.success("Exercise plan created!");
    setCurrent(3);
  };

  // Define the steps with enhanced UI
  const steps = [
    {
      title: "Basic Info",
      icon: <UserOutlined />,
      content: (
        <Card style={styles.stepCard}>
          <Title level={4} style={{ marginBottom: "24px" }}>
            Tell us about your fitness journey
          </Title>
          <Form form={form} layout="vertical" onFinish={handleBasicInfoSubmit}>
            <Form.Item
              name="name"
              label="Fitness Path Name"
              rules={[
                {
                  required: true,
                  message: "Please enter a name for your fitness path",
                },
              ]}
            >
              <Input
                placeholder="e.g., Summer Shred 2025"
                size="large"
                style={{ borderRadius: "6px" }}
              />
            </Form.Item>

            <Form.Item
              name="description"
              label="Description"
              rules={[
                {
                  required: true,
                  message: "Please describe your fitness path",
                },
              ]}
            >
              <Input.TextArea
                placeholder="Describe your fitness goals and what you want to achieve"
                rows={4}
                style={{ borderRadius: "6px" }}
              />
            </Form.Item>

            <Form.Item style={{ marginTop: "32px", textAlign: "right" }}>
              <Button
                type="primary"
                htmlType="submit"
                loading={submitting}
                style={styles.button}
                size="large"
                icon={<ArrowRightOutlined />}
              >
                Continue
              </Button>
            </Form.Item>
          </Form>
        </Card>
      ),
    },
    {
      title: "Personal Profile",
      icon: <UserOutlined />,
      content: (
        <Card style={styles.stepCard}>
          <Title level={4} style={{ marginBottom: "24px" }}>
            Build Your Fitness Profile
          </Title>
          <ActivityTypes
            onActivityTypesGenerated={handleActivityTypesGenerated}
          />
          <div style={{ marginTop: "24px", textAlign: "right" }}>
            <Button
              onClick={() => setCurrent(0)}
              style={{ ...styles.secondaryButton, marginRight: "12px" }}
              icon={<ArrowLeftOutlined />}
            >
              Previous
            </Button>
            <Button
              type="primary"
              onClick={() => {
                if (activityTypes.length > 0) {
                  setCurrent(2);
                } else {
                  message.warning("Please generate activity types first");
                }
              }}
              disabled={activityTypes.length === 0}
              style={styles.button}
              icon={<ArrowRightOutlined />}
            >
              Continue
            </Button>
          </div>
        </Card>
      ),
    },
    {
      title: "Exercise Plan",
      icon: <FireOutlined />,
      content: (
        <Card style={styles.stepCard}>
          <Title level={4} style={{ marginBottom: "24px" }}>
            Create Your Custom Workout Plan
          </Title>
          <ExercisePlanBuilder
            availableActivities={activityTypes}
            onPlanSubmit={handleExercisePlanSubmit}
            fitnessPathId={fitnessPathId}
          />
          <div style={{ marginTop: "24px", textAlign: "right" }}>
            <Button
              onClick={() => setCurrent(1)}
              style={{ ...styles.secondaryButton, marginRight: "12px" }}
              icon={<ArrowLeftOutlined />}
            >
              Previous
            </Button>
          </div>
        </Card>
      ),
    },
    {
      title: "Completed",
      icon: <CheckCircleOutlined />,
      content: (
        <Card style={styles.stepCard}>
          <Result
            status="success"
            title="Your Fitness Plan Has Been Created!"
            subTitle="You can now start following your personalized fitness journey."
            icon={
              <div
                style={{
                  width: "80px",
                  height: "80px",
                  borderRadius: "50%",
                  background: theme.gradients.main,
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                }}
              >
                <CheckCircleOutlined
                  style={{
                    fontSize: "48px",
                    color: "white",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                  }}
                />
              </div>
            }
            extra={[
              <Button
                onClick={goDashboard}
                type="primary"
                key="dashboard"
                size="large"
                style={{
                  ...styles.button,
                  background: theme.gradients.main,
                  height: "48px",
                  fontSize: "16px",
                  padding: "0 32px",
                }}
              >
                Go to Dashboard
              </Button>,
            ]}
          />

          {/* Added follow-up suggestions */}
          <div style={{ marginTop: "48px" }}>
            <Title level={4}>What&apos;s Next?</Title>
            <Row gutter={[16, 16]} style={{ marginTop: "16px" }}>
              <Col xs={24} md={8}>
                <Card hoverable style={{ height: "100%" }}>
                  <Space
                    direction="vertical"
                    align="center"
                    style={{ width: "100%", textAlign: "center" }}
                  >
                    <Avatar
                      size={64}
                      style={{ backgroundColor: theme.colors.primary }}
                    >
                      1
                    </Avatar>
                    <Text strong>Track Your Progress</Text>
                    <Text type="secondary">
                      Log your workouts and measurements to see your improvement
                      over time
                    </Text>
                  </Space>
                </Card>
              </Col>
              <Col xs={24} md={8}>
                <Card hoverable style={{ height: "100%" }}>
                  <Space
                    direction="vertical"
                    align="center"
                    style={{ width: "100%", textAlign: "center" }}
                  >
                    <Avatar
                      size={64}
                      style={{ backgroundColor: theme.colors.secondary }}
                    >
                      2
                    </Avatar>
                    <Text strong>Earn XP</Text>
                    <Text type="secondary">
                      Level up and upgrade your avatar
                    </Text>
                  </Space>
                </Card>
              </Col>
              <Col xs={24} md={8}>
                <Card hoverable style={{ height: "100%" }}>
                  <Space
                    direction="vertical"
                    align="center"
                    style={{ width: "100%", textAlign: "center" }}
                  >
                    <Avatar
                      size={64}
                      style={{ backgroundColor: theme.colors.tertiary }}
                    >
                      3
                    </Avatar>
                    <Text strong>Challenge yourself</Text>
                    <Text type="secondary">
                      Check your stats to get better everyday
                    </Text>
                  </Space>
                </Card>
              </Col>
            </Row>
          </div>
        </Card>
      ),
    },
  ];

  return (
    <Content style={styles.container}>
      {/* Welcome Card with Gradient Background */}
      <Card style={styles.welcomeCard}>
        <Space align="center" style={{ marginBottom: "16px" }}>
          <RocketOutlined
            style={{ fontSize: "36px", color: theme.colors.white }}
          />
          <Badge
            count="Premium"
            style={{
              backgroundColor: "rgba(255, 255, 255, 0.2)",
              color: theme.colors.white,
              fontWeight: "bold",
              fontSize: "12px",
            }}
          />
        </Space>
        <Title level={2} style={styles.welcomeTitle}>
          Welcome, {currentUser?.name || "Fitness Enthusiast"}!
        </Title>
        <Paragraph style={styles.welcomeText}>
          You&apos;re about to create a personalized fitness plan designed
          specifically for your body and goals. Our AI-powered system will guide
          you through creating an effective exercise regimen that fits your
          lifestyle.
        </Paragraph>

        {current === 0 && <FitnessStats />}
      </Card>

      <Steps
        current={current}
        items={steps.map((item, index) => ({
          key: index,
          title: item.title,
          icon: item.icon,
        }))}
        progressDot
        style={{
          marginBottom: "32px",
          ...styles.steps,
        }}
      />

      {/* Dynamic Content based on current step */}
      <div>{steps[current].content}</div>
    </Content>
  );
};

export default StepBasedFitnessPlanner;
