import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ConfigProvider, App as AntdApp } from "antd";  // ✅ ADD App here
import { AuthProvider } from "@/providers/auth-provider";
import { UserProvider } from "@/providers/user-provider";
import { StepsProvider } from "@/providers/fitnesspath/step-provider";
import { WeightProvider } from "@/providers/fitnesspath/weight-provider";
import { FitnessPathProvider } from "@/providers/fitnesspath/fitness-provider";
import { ActivityTypeProvider } from "@/providers/fitnesspath/activity-type-provider";
import { ExercisePlanProvider } from "@/providers/fitnesspath/exercise-plan-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "LifeQuest",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConfigProvider
      theme={{
        token: {
          colorPrimary: "#A0A2ED",
          colorSuccess: "#8EECF5",
          colorInfo: "#D0BDF4",
          borderRadius: 12,
        },
      }}
    >
      <AntdApp> 
        <html lang="en">
          <AuthProvider>
            <UserProvider><FitnessPathProvider>
              <StepsProvider><WeightProvider><ActivityTypeProvider><ExercisePlanProvider>
                <body className={`${geistSans.variable} ${geistMono.variable}`}>
                  {children}
                </body></ExercisePlanProvider></ActivityTypeProvider></WeightProvider>
              </StepsProvider></FitnessPathProvider>
            </UserProvider>
          </AuthProvider>
        </html>
      </AntdApp>
    </ConfigProvider>
  );
}
