import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ConfigProvider, App as AntdApp } from "antd";
import { AuthProvider } from "@/providers/auth-provider";
import { UserProvider } from "@/providers/user-provider";
import { StepsProvider } from "@/providers/fitnesspath/step-provider";
import { WeightProvider } from "@/providers/fitnesspath/weight-provider";
import { FitnessPathProvider } from "@/providers/fitnesspath/fitness-provider";
import { ActivityTypeProvider } from "@/providers/fitnesspath/activity-provider";
import { ExercisePlanProvider } from "@/providers/fitnesspath/exercise-plan";
import { PathsProvider } from "@/providers/paths";
import { HealthPathProvider } from "@/providers/health-path-provider/health-provider";
import { MealPlanProvider } from "@/providers/health-path-provider/meal-plan";
import { MealProvider } from "@/providers/health-path-provider/meal-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "LifeQuest",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <ConfigProvider
          theme={{
            token: {
              colorPrimary: "#A0A2ED",
              colorSuccess: "#8EECF5",
              colorInfo: "#D0BDF4",
              borderRadius: 12,
            },
          }}
        >
          <AntdApp>
            <AuthProvider>
              <UserProvider>
                <PathsProvider>
                  <FitnessPathProvider>
                    <HealthPathProvider>
                      <MealPlanProvider>
                        <MealProvider>
                          <StepsProvider>
                            <WeightProvider>
                              <ActivityTypeProvider>
                                <ExercisePlanProvider>
                                  {children}
                                </ExercisePlanProvider>
                              </ActivityTypeProvider>
                            </WeightProvider>
                          </StepsProvider>
                        </MealProvider>
                      </MealPlanProvider>
                    </HealthPathProvider>
                  </FitnessPathProvider>
                </PathsProvider>
              </UserProvider>
            </AuthProvider>
          </AntdApp>
        </ConfigProvider>
      </body>
    </html>
  );
}
